# Generated by Django 2.2.5 on 2019-10-27 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='consulting',
            fields=[
                ('si', models.CharField(max_length=100)),
                ('gu', models.CharField(max_length=100)),
                ('dong', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('theta0', models.FloatField()),
                ('theta1', models.FloatField()),
                ('theta2', models.FloatField()),
                ('theta3', models.FloatField()),
                ('theta4', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='middleman',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('dong', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('pw', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('power', models.IntegerField()),
            ],
        ),
    ]
