# Generated by Django 2.2.2 on 2019-09-23 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='consultant',
            fields=[
                ('si', models.CharField(max_length=100)),
                ('gu', models.CharField(max_length=100)),
                ('dong', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('theta', models.FloatField()),
            ],
        ),
    ]
