# Generated by Django 2.2.2 on 2019-09-24 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_consultant'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='consultant',
            new_name='consulting',
        ),
    ]
